<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYmsixj2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYmsixj2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYmsixj2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYmsixj2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYmsixj2\appProdProjectContainer([
    'container.build_hash' => 'Ymsixj2',
    'container.build_id' => '6734a430',
    'container.build_time' => 1689063941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYmsixj2');
