<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZo1bfxk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZo1bfxk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZo1bfxk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZo1bfxk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZo1bfxk\appDevDebugProjectContainer([
    'container.build_hash' => 'Zo1bfxk',
    'container.build_id' => '176027e0',
    'container.build_time' => 1689074057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZo1bfxk');
